## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN'])

In [3]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

NAME 19568
APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [4]:
# Look at APPLICATION_TYPE value counts for binning
counts = application_df['NAME'].value_counts()
counts

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
UTAH FRIENDS OF TIBET FOUNDATION                      1
SI JAK NFP INC                                        1
FACPSU                                                1
NATIONAL VIETNAMESE CATHOLIC REVIVAL                  1
MOUNTAIN VIEW PARK & RECREATION COUNCIL INC           1
Name: NAME, Length: 19568, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<300].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classificationbinning = application_df['CLASSIFICATION'].value_counts()
classificationbinning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2600        1
C2570        1
C8210        1
C1370        1
C2500        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = classificationbinning[classificationbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1600        5
C1257        5
C2710        3
C1260        3
C0           3
C1246        2
C1234        2
C3200        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classificationbinning[classificationbinning<150].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1003
C7000      777
C1700      287
C4000      194
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,NAME_13TH BOMB SQUADRON ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]
hidden_nodes1=7
hidden_nodes2=14
hidden_nodes3=21

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes1, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 137361

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 21)                315

 dense_3 (Dense)             (None, 1)                 22

=================================================================
Total params: 137,810
Trainable params: 137,810
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 5s 6ms/step - loss: 0.5273 - accuracy: 0.7295 - val_loss: 0.4657 - val_accuracy: 0.7805
Epoch 2/100
684/684 [==============================] - 4s 6ms/step - loss: 0.3379 - accuracy: 0.8390 - val_loss: 0.5661 - val_accuracy: 0.6059
Epoch 3/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1867 - accuracy: 0.9243 - val_loss: 0.4570 - val_accuracy: 0.7803
Epoch 4/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1287 - accuracy: 0.9479 - val_loss: 0.4561 - val_accuracy: 0.7782
Epoch 5/100
684/684 [==============================] - 3s 5ms/step - loss: 0.1024 - accuracy: 0.9581 - val_loss: 0.6084 - val_accuracy: 0.7981
Epoch 6/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0972 - accuracy: 0.9597 - val_loss: 0.6003 - val_accuracy: 0.7992
Epoch 7/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0954 - accuracy: 0.9590 - val_loss: 0.7524 - val_accuracy: 0.7976
Epoch 8/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0937 - accuracy: 0.9591 - val_loss: 0.7501 - val_accuracy: 0.7992
Epoch 9/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0930 - accuracy: 0.9597 - val_loss: 0.7990 - val_accuracy: 0.7992
Epoch 10/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0919 - accuracy: 0.9605 - val_loss: 0.7539 - val_accuracy: 0.7984
Epoch 11/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0914 - accuracy: 0.9605 - val_loss: 0.9386 - val_accuracy: 0.8018
Epoch 12/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0904 - accuracy: 0.9610 - val_loss: 0.7572 - val_accuracy: 0.8002
Epoch 13/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0907 - accuracy: 0.9604 - val_loss: 0.8255 - val_accuracy: 0.8018
Epoch 14/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0902 - accuracy: 0.9610 - val_loss: 0.9815 - val_accuracy: 0.8018
Epoch 15/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0892 - accuracy: 0.9614 - val_loss: 0.9670 - val_accuracy: 0.8015
Epoch 16/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0884 - accuracy: 0.9618 - val_loss: 0.9717 - val_accuracy: 0.8010
Epoch 17/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0885 - accuracy: 0.9611 - val_loss: 1.1409 - val_accuracy: 0.8010
Epoch 18/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0887 - accuracy: 0.9618 - val_loss: 1.0927 - val_accuracy: 0.8010
Epoch 19/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0890 - accuracy: 0.9613 - val_loss: 1.0002 - val_accuracy: 0.7974
Epoch 20/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0884 - accuracy: 0.9618 - val_loss: 1.4058 - val_accuracy: 0.8010
Epoch 21/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0874 - accuracy: 0.9618 - val_loss: 1.5976 - val_accuracy: 0.8012
Epoch 22/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0873 - accuracy: 0.9621 - val_loss: 1.3132 - val_accuracy: 0.7992
Epoch 23/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0871 - accuracy: 0.9620 - val_loss: 1.3649 - val_accuracy: 0.8012
Epoch 24/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0871 - accuracy: 0.9619 - val_loss: 1.4970 - val_accuracy: 0.8012
Epoch 25/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0866 - accuracy: 0.9622 - val_loss: 1.5613 - val_accuracy: 0.8015
Epoch 26/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0868 - accuracy: 0.9623 - val_loss: 1.5050 - val_accuracy: 0.8007
Epoch 27/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0867 - accuracy: 0.9625 - val_loss: 1.5398 - val_accuracy: 0.8018
Epoch 28/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0866 - accuracy: 0.9623 - val_loss: 1.9261 - val_accuracy: 0.8012
Epoch 29/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0861 - accuracy: 0.9626 - val_loss: 1.5625 - val_accuracy: 0.7997
Epoch 30/100
684/684 [==============================] - 4s 5ms/step - loss: 0.0862 - accuracy: 0.9622 - val_loss: 1.5219 - val_accuracy: 0.8028
Epoch 31/100
684/684 [==============================] - 4s 5ms/step - loss: 0.0857 - accuracy: 0.9630 - val_loss: 1.6815 - val_accuracy: 0.8020
Epoch 32/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0857 - accuracy: 0.9630 - val_loss: 1.7344 - val_accuracy: 0.8018
Epoch 33/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0854 - accuracy: 0.9633 - val_loss: 1.8340 - val_accuracy: 0.8007
Epoch 34/100
684/684 [==============================] - 4s 6ms/step - loss: 0.0852 - accuracy: 0.9630 - val_loss: 1.7217 - val_accuracy: 0.8015
Epoch 35/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0850 - accuracy: 0.9637 - val_loss: 1.9551 - val_accuracy: 0.8018
Epoch 36/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0853 - accuracy: 0.9629 - val_loss: 1.7663 - val_accuracy: 0.8031
Epoch 37/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0849 - accuracy: 0.9641 - val_loss: 1.8969 - val_accuracy: 0.8012
Epoch 38/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0841 - accuracy: 0.9641 - val_loss: 1.7165 - val_accuracy: 0.8025
Epoch 39/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0837 - accuracy: 0.9644 - val_loss: 1.6889 - val_accuracy: 0.8020
Epoch 40/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0835 - accuracy: 0.9643 - val_loss: 1.8036 - val_accuracy: 0.8007
Epoch 41/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0837 - accuracy: 0.9635 - val_loss: 1.7540 - val_accuracy: 0.8005
Epoch 42/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0836 - accuracy: 0.9645 - val_loss: 1.5799 - val_accuracy: 0.8023
Epoch 43/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0836 - accuracy: 0.9645 - val_loss: 1.5764 - val_accuracy: 0.8012
Epoch 44/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0834 - accuracy: 0.9646 - val_loss: 1.7795 - val_accuracy: 0.8020
Epoch 45/100
684/684 [==============================] - 4s 5ms/step - loss: 0.0832 - accuracy: 0.9643 - val_loss: 1.6598 - val_accuracy: 0.8018
Epoch 46/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0828 - accuracy: 0.9646 - val_loss: 1.8217 - val_accuracy: 0.8018
Epoch 47/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0834 - accuracy: 0.9646 - val_loss: 1.8236 - val_accuracy: 0.7950
Epoch 48/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0832 - accuracy: 0.9646 - val_loss: 1.5864 - val_accuracy: 0.8015
Epoch 49/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0832 - accuracy: 0.9641 - val_loss: 1.5533 - val_accuracy: 0.8020
Epoch 50/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0828 - accuracy: 0.9647 - val_loss: 1.7109 - val_accuracy: 0.8018
Epoch 51/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0830 - accuracy: 0.9645 - val_loss: 1.5120 - val_accuracy: 0.8015
Epoch 52/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0827 - accuracy: 0.9647 - val_loss: 1.6892 - val_accuracy: 0.8015
Epoch 53/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0827 - accuracy: 0.9644 - val_loss: 1.6657 - val_accuracy: 0.8018
Epoch 54/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0832 - accuracy: 0.9634 - val_loss: 1.5028 - val_accuracy: 0.8018
Epoch 55/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0828 - accuracy: 0.9645 - val_loss: 1.5413 - val_accuracy: 0.8023
Epoch 56/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0828 - accuracy: 0.9650 - val_loss: 1.4858 - val_accuracy: 0.8023
Epoch 57/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0821 - accuracy: 0.9652 - val_loss: 1.5985 - val_accuracy: 0.8018

Epoch 58/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0827 - accuracy: 0.9647 - val_loss: 1.4661 - val_accuracy: 0.8015
Epoch 59/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0832 - accuracy: 0.9640 - val_loss: 1.2230 - val_accuracy: 0.8005
Epoch 60/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0827 - accuracy: 0.9648 - val_loss: 1.3576 - val_accuracy: 0.8015
Epoch 61/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0822 - accuracy: 0.9646 - val_loss: 1.6257 - val_accuracy: 0.8018
Epoch 62/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9648 - val_loss: 1.6030 - val_accuracy: 0.8015
Epoch 63/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0823 - accuracy: 0.9646 - val_loss: 1.5604 - val_accuracy: 0.8010
Epoch 64/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0818 - accuracy: 0.9646 - val_loss: 1.6442 - val_accuracy: 0.8018
Epoch 65/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0824 - accuracy: 0.9644 - val_loss: 1.7365 - val_accuracy: 0.8018
Epoch 66/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0820 - accuracy: 0.9643 - val_loss: 1.7144 - val_accuracy: 0.8015
Epoch 67/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0819 - accuracy: 0.9650 - val_loss: 1.7718 - val_accuracy: 0.8018
Epoch 68/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9644 - val_loss: 1.9358 - val_accuracy: 0.8020
Epoch 69/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9651 - val_loss: 1.8775 - val_accuracy: 0.8010
Epoch 70/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9650 - val_loss: 2.0562 - val_accuracy: 0.8010
Epoch 71/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9653 - val_loss: 1.8410 - val_accuracy: 0.8012
Epoch 72/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9650 - val_loss: 1.9016 - val_accuracy: 0.8012
Epoch 73/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9645 - val_loss: 1.8564 - val_accuracy: 0.8015
Epoch 74/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9647 - val_loss: 1.9764 - val_accuracy: 0.8015
Epoch 75/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9648 - val_loss: 1.7523 - val_accuracy: 0.8002
Epoch 76/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9645 - val_loss: 1.8211 - val_accuracy: 0.8015
Epoch 77/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9645 - val_loss: 2.2136 - val_accuracy: 0.8007
Epoch 78/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0819 - accuracy: 0.9649 - val_loss: 1.9809 - val_accuracy: 0.8012
Epoch 79/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9648 - val_loss: 1.8180 - val_accuracy: 0.8005
Epoch 80/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0811 - accuracy: 0.9651 - val_loss: 1.9588 - val_accuracy: 0.8007
Epoch 81/100
684/684 [==============================] - 4s 6ms/step - loss: 0.0814 - accuracy: 0.9650 - val_loss: 1.9096 - val_accuracy: 0.8007
Epoch 82/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0812 - accuracy: 0.9649 - val_loss: 2.1173 - val_accuracy: 0.8015
Epoch 83/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9645 - val_loss: 2.0474 - val_accuracy: 0.8005
Epoch 84/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9647 - val_loss: 2.1102 - val_accuracy: 0.8012
Epoch 85/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9647 - val_loss: 2.0293 - val_accuracy: 0.8010
Epoch 86/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0810 - accuracy: 0.9649 - val_loss: 1.9448 - val_accuracy: 0.8018
Epoch 87/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0812 - accuracy: 0.9649 - val_loss: 1.9266 - val_accuracy: 0.8018
Epoch 88/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0808 - accuracy: 0.9648 - val_loss: 2.2542 - val_accuracy: 0.8028
Epoch 89/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0811 - accuracy: 0.9654 - val_loss: 2.5711 - val_accuracy: 0.8020
Epoch 90/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0809 - accuracy: 0.9650 - val_loss: 1.9987 - val_accuracy: 0.8015
Epoch 91/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0811 - accuracy: 0.9653 - val_loss: 1.8585 - val_accuracy: 0.8010
Epoch 92/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0806 - accuracy: 0.9651 - val_loss: 2.1353 - val_accuracy: 0.8010
Epoch 93/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0810 - accuracy: 0.9650 - val_loss: 1.9627 - val_accuracy: 0.8015
Epoch 94/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0810 - accuracy: 0.9651 - val_loss: 2.1577 - val_accuracy: 0.8031
Epoch 95/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0807 - accuracy: 0.9654 - val_loss: 2.6700 - val_accuracy: 0.8010
Epoch 96/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0804 - accuracy: 0.9653 - val_loss: 2.4787 - val_accuracy: 0.8015
Epoch 97/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0803 - accuracy: 0.9651 - val_loss: 2.5212 - val_accuracy: 0.8012
Epoch 98/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0806 - accuracy: 0.9653 - val_loss: 2.5906 - val_accuracy: 0.8002
Epoch 99/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0805 - accuracy: 0.9652 - val_loss: 2.6646 - val_accuracy: 0.8012
Epoch 100/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0805 - accuracy: 0.9650 - val_loss: 2.8511 - val_accuracy: 0.8005

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.9846 - accuracy: 0.5678 - 567ms/epoch - 2ms/step
Loss: 0.9845994710922241, Accuracy: 0.5678133964538574

In [16]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization1.h5')