## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN'])

In [3]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

NAME 19568
APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [4]:
# Look at APPLICATION_TYPE value counts for binning
counts = application_df['NAME'].value_counts()
counts

PARENT BOOSTER USA INC                                         1260
TOPS CLUB INC                                                   765
UNITED STATES BOWLING CONGRESS INC                              700
WASHINGTON STATE UNIVERSITY                                     492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                 408
                                                               ...
WASHOE BARTON MEDICAL CLINIC A NEVADA NONPROFIT CORPORATION       1
FITNESS CHAMPIONS                                                 1
CENTRAL PARK LIONS CLUB FOUNDATION                                1
TEXAS ASSOCIATION FOR THE EDUCATION OF YOUNG CHILDREN             1
GERMAN SHORTHAIRED POINTER RESCUE OF OKLAHOMA INCORPORATED        1
Name: NAME, Length: 19568, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<10].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classificationbinning = application_df['CLASSIFICATION'].value_counts()
classificationbinning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2561        1
C1283        1
C1580        1
C2570        1
C3700        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = classificationbinning[classificationbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1278       10
C1238       10
C1237        9
C1235        9
C7210        7
C2400        6
C1720        6
C4100        6
C1600        5
C1257        5
C0           3
C1260        3
C2710        3
C1256        2
C3200        2
C1267        2
C1234        2
C1246        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classificationbinning[classificationbinning<100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,NAME_13TH BOMB SQUADRON ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]
hidden_nodes1=7
hidden_nodes2=14
hidden_nodes3=21

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes1, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 137382

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 21)                315

 dense_3 (Dense)             (None, 1)                 22

=================================================================
Total params: 137,831
Trainable params: 137,831
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 5s 6ms/step - loss: 0.5223 - accuracy: 0.7395 - val_loss: 0.4537 - val_accuracy: 0.7896
Epoch 2/100
684/684 [==============================] - 3s 5ms/step - loss: 0.3580 - accuracy: 0.8327 - val_loss: 0.5261 - val_accuracy: 0.6256
Epoch 3/100
684/684 [==============================] - 3s 5ms/step - loss: 0.1954 - accuracy: 0.9253 - val_loss: 0.4832 - val_accuracy: 0.7411
Epoch 4/100
684/684 [==============================] - 4s 5ms/step - loss: 0.1376 - accuracy: 0.9453 - val_loss: 0.8497 - val_accuracy: 0.7966
Epoch 5/100
684/684 [==============================] - 3s 5ms/step - loss: 0.1173 - accuracy: 0.9535 - val_loss: 1.0502 - val_accuracy: 0.7968
Epoch 6/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1045 - accuracy: 0.9574 - val_loss: 1.4009 - val_accuracy: 0.7968
Epoch 7/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1002 - accuracy: 0.9587 - val_loss: 1.1401 - val_accuracy: 0.7992
Epoch 8/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0987 - accuracy: 0.9589 - val_loss: 1.0965 - val_accuracy: 0.7981
Epoch 9/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0965 - accuracy: 0.9591 - val_loss: 1.3479 - val_accuracy: 0.7994
Epoch 10/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0944 - accuracy: 0.9609 - val_loss: 1.1877 - val_accuracy: 0.7937
Epoch 11/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0944 - accuracy: 0.9594 - val_loss: 1.1745 - val_accuracy: 0.7966
Epoch 12/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0937 - accuracy: 0.9603 - val_loss: 1.2708 - val_accuracy: 0.7940
Epoch 13/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0935 - accuracy: 0.9596 - val_loss: 1.3475 - val_accuracy: 0.7987
Epoch 14/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0925 - accuracy: 0.9605 - val_loss: 1.2191 - val_accuracy: 0.7958
Epoch 15/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0919 - accuracy: 0.9605 - val_loss: 1.3015 - val_accuracy: 0.7997
Epoch 16/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0921 - accuracy: 0.9607 - val_loss: 1.5249 - val_accuracy: 0.7992
Epoch 17/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0907 - accuracy: 0.9611 - val_loss: 1.3410 - val_accuracy: 0.7997
Epoch 18/100
684/684 [==============================] - 4s 6ms/step - loss: 0.0899 - accuracy: 0.9608 - val_loss: 1.3352 - val_accuracy: 0.7987
Epoch 19/100
684/684 [==============================] - 4s 5ms/step - loss: 0.0895 - accuracy: 0.9606 - val_loss: 1.8024 - val_accuracy: 0.7976
Epoch 20/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0897 - accuracy: 0.9614 - val_loss: 1.5207 - val_accuracy: 0.7966
Epoch 21/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0894 - accuracy: 0.9616 - val_loss: 1.5591 - val_accuracy: 0.7997
Epoch 22/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0887 - accuracy: 0.9614 - val_loss: 1.3374 - val_accuracy: 0.7997
Epoch 23/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0887 - accuracy: 0.9612 - val_loss: 1.4223 - val_accuracy: 0.7999
Epoch 24/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0888 - accuracy: 0.9607 - val_loss: 1.3670 - val_accuracy: 0.8002
Epoch 25/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0878 - accuracy: 0.9614 - val_loss: 1.4749 - val_accuracy: 0.7981
Epoch 26/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0881 - accuracy: 0.9614 - val_loss: 1.2422 - val_accuracy: 0.7974
Epoch 27/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0874 - accuracy: 0.9619 - val_loss: 1.3585 - val_accuracy: 0.7997
Epoch 28/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0876 - accuracy: 0.9621 - val_loss: 1.4720 - val_accuracy: 0.7994
Epoch 29/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0871 - accuracy: 0.9620 - val_loss: 1.5123 - val_accuracy: 0.8005
Epoch 30/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0872 - accuracy: 0.9623 - val_loss: 1.5003 - val_accuracy: 0.7997
Epoch 31/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0874 - accuracy: 0.9623 - val_loss: 1.2534 - val_accuracy: 0.7992
Epoch 32/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0869 - accuracy: 0.9623 - val_loss: 1.2289 - val_accuracy: 0.8005
Epoch 33/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0870 - accuracy: 0.9619 - val_loss: 1.7330 - val_accuracy: 0.7999
Epoch 34/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0869 - accuracy: 0.9620 - val_loss: 1.5139 - val_accuracy: 0.7997
Epoch 35/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0857 - accuracy: 0.9622 - val_loss: 2.1550 - val_accuracy: 0.7999
Epoch 36/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0867 - accuracy: 0.9625 - val_loss: 1.6026 - val_accuracy: 0.7999
Epoch 37/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0865 - accuracy: 0.9620 - val_loss: 1.3569 - val_accuracy: 0.8007
Epoch 38/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0857 - accuracy: 0.9629 - val_loss: 1.8456 - val_accuracy: 0.8002
Epoch 39/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0856 - accuracy: 0.9628 - val_loss: 2.1779 - val_accuracy: 0.7981
Epoch 40/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0859 - accuracy: 0.9630 - val_loss: 1.7799 - val_accuracy: 0.7997
Epoch 41/100
684/684 [==============================] - 4s 6ms/step - loss: 0.0852 - accuracy: 0.9635 - val_loss: 1.6609 - val_accuracy: 0.8005
Epoch 42/100
684/684 [==============================] - 4s 6ms/step - loss: 0.0847 - accuracy: 0.9640 - val_loss: 1.7551 - val_accuracy: 0.7997
Epoch 43/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0848 - accuracy: 0.9641 - val_loss: 1.8155 - val_accuracy: 0.8002
Epoch 44/100
684/684 [==============================] - 4s 5ms/step - loss: 0.0855 - accuracy: 0.9635 - val_loss: 1.7337 - val_accuracy: 0.7997
Epoch 45/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0847 - accuracy: 0.9636 - val_loss: 2.1063 - val_accuracy: 0.7997
Epoch 46/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0845 - accuracy: 0.9639 - val_loss: 2.2243 - val_accuracy: 0.7999
Epoch 47/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0840 - accuracy: 0.9643 - val_loss: 2.4861 - val_accuracy: 0.7992
Epoch 48/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0842 - accuracy: 0.9638 - val_loss: 2.8617 - val_accuracy: 0.7909
Epoch 49/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0843 - accuracy: 0.9642 - val_loss: 2.3988 - val_accuracy: 0.7987
Epoch 50/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0842 - accuracy: 0.9643 - val_loss: 2.6628 - val_accuracy: 0.7999
Epoch 51/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0838 - accuracy: 0.9639 - val_loss: 2.5792 - val_accuracy: 0.7999
Epoch 52/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0836 - accuracy: 0.9644 - val_loss: 2.9880 - val_accuracy: 0.7981
Epoch 53/100
684/684 [==============================] - 3s 5ms/step - loss: 0.0839 - accuracy: 0.9646 - val_loss: 2.7353 - val_accuracy: 0.7999
Epoch 54/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0833 - accuracy: 0.9646 - val_loss: 2.8654 - val_accuracy: 0.8005
Epoch 55/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0835 - accuracy: 0.9645 - val_loss: 3.0596 - val_accuracy: 0.8002
Epoch 56/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0833 - accuracy: 0.9647 - val_loss: 2.9347 - val_accuracy: 0.8002
Epoch 57/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0832 - accuracy: 0.9649 - val_loss: 3.1932 - val_accuracy: 0.7984

Epoch 58/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0834 - accuracy: 0.9646 - val_loss: 3.0064 - val_accuracy: 0.7992
Epoch 59/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0833 - accuracy: 0.9648 - val_loss: 3.2264 - val_accuracy: 0.8007
Epoch 60/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0831 - accuracy: 0.9646 - val_loss: 3.2159 - val_accuracy: 0.8005
Epoch 61/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0830 - accuracy: 0.9651 - val_loss: 3.5109 - val_accuracy: 0.8005
Epoch 62/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0828 - accuracy: 0.9648 - val_loss: 3.7134 - val_accuracy: 0.8007
Epoch 63/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0828 - accuracy: 0.9649 - val_loss: 3.3110 - val_accuracy: 0.7999
Epoch 64/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0826 - accuracy: 0.9652 - val_loss: 3.7409 - val_accuracy: 0.7997
Epoch 65/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0835 - accuracy: 0.9652 - val_loss: 3.2616 - val_accuracy: 0.8007
Epoch 66/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0826 - accuracy: 0.9651 - val_loss: 3.2825 - val_accuracy: 0.7997
Epoch 67/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0825 - accuracy: 0.9646 - val_loss: 2.8273 - val_accuracy: 0.7992
Epoch 68/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0822 - accuracy: 0.9651 - val_loss: 3.3513 - val_accuracy: 0.8002
Epoch 69/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0826 - accuracy: 0.9652 - val_loss: 3.6412 - val_accuracy: 0.7999
Epoch 70/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0823 - accuracy: 0.9651 - val_loss: 3.2272 - val_accuracy: 0.7999
Epoch 71/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0827 - accuracy: 0.9651 - val_loss: 3.1604 - val_accuracy: 0.7997
Epoch 72/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0823 - accuracy: 0.9654 - val_loss: 3.4124 - val_accuracy: 0.7999
Epoch 73/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0822 - accuracy: 0.9649 - val_loss: 3.9790 - val_accuracy: 0.8005
Epoch 74/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0824 - accuracy: 0.9653 - val_loss: 3.1651 - val_accuracy: 0.7994
Epoch 75/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9655 - val_loss: 3.7608 - val_accuracy: 0.7999
Epoch 76/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0826 - accuracy: 0.9658 - val_loss: 4.3916 - val_accuracy: 0.7994
Epoch 77/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0819 - accuracy: 0.9654 - val_loss: 3.7897 - val_accuracy: 0.7992
Epoch 78/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0821 - accuracy: 0.9652 - val_loss: 3.5890 - val_accuracy: 0.8002
Epoch 79/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9654 - val_loss: 3.5713 - val_accuracy: 0.8005
Epoch 80/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9655 - val_loss: 3.7305 - val_accuracy: 0.7997
Epoch 81/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0819 - accuracy: 0.9655 - val_loss: 3.7219 - val_accuracy: 0.7989
Epoch 82/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9656 - val_loss: 4.2015 - val_accuracy: 0.7999
Epoch 83/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9653 - val_loss: 3.5713 - val_accuracy: 0.7999
Epoch 84/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9657 - val_loss: 4.3993 - val_accuracy: 0.8002
Epoch 85/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9654 - val_loss: 3.8393 - val_accuracy: 0.7997
Epoch 86/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9658 - val_loss: 4.3452 - val_accuracy: 0.7999
Epoch 87/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9654 - val_loss: 4.8479 - val_accuracy: 0.8005
Epoch 88/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9657 - val_loss: 4.8417 - val_accuracy: 0.8002
Epoch 89/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9656 - val_loss: 5.6844 - val_accuracy: 0.7999
Epoch 90/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9655 - val_loss: 5.9898 - val_accuracy: 0.7989
Epoch 91/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0811 - accuracy: 0.9659 - val_loss: 5.7294 - val_accuracy: 0.8005
Epoch 92/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0817 - accuracy: 0.9655 - val_loss: 5.3103 - val_accuracy: 0.7992
Epoch 93/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9657 - val_loss: 5.7405 - val_accuracy: 0.7999
Epoch 94/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0811 - accuracy: 0.9657 - val_loss: 5.8578 - val_accuracy: 0.7997
Epoch 95/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0813 - accuracy: 0.9658 - val_loss: 6.4035 - val_accuracy: 0.7997
Epoch 96/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0813 - accuracy: 0.9657 - val_loss: 6.4287 - val_accuracy: 0.7999
Epoch 97/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0813 - accuracy: 0.9657 - val_loss: 6.6180 - val_accuracy: 0.7999
Epoch 98/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9658 - val_loss: 6.1242 - val_accuracy: 0.8005
Epoch 99/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0811 - accuracy: 0.9659 - val_loss: 6.1881 - val_accuracy: 0.8002
Epoch 100/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9657 - val_loss: 5.3354 - val_accuracy: 0.7994

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.7580 - accuracy: 0.6819 - 695ms/epoch - 3ms/step
Loss: 0.7580328583717346, Accuracy: 0.6818658709526062

In [17]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization1.h5')